apiVersion: batch/v1
kind: Job
metadata:
  name: wrk-load
spec:
  backoffLimit: 1
  ttlSecondsAfterFinished: 30    # cleans up Job+Pods 30s after completion
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: wrk
        image: skandyla/wrk:latest
        args:
          - "-t1"                        # 4 worker threads
          - "-c50"                       # 100 concurrent connections
          - "-d60s"                      # run for 60 seconds
          - "--latency"                  # report latency percentiles
          - "http://nginx-service/"      # target service (ClusterDNS)