apiVersion: apps/v1
kind: Deployment
metadata:
  name: predictor-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: predictor-api
  template:
    metadata:
      labels:
        app: predictor-api
    spec:
      containers:
      - name: predictor
        image: your-registry/predictor-api:v1
        ports:
        - containerPort: 5000
        resources:
          requests:
            cpu: "500m"
            memory: "512Mi"
          limits:
            cpu: "1000m"
            memory: "1Gi"
        livenessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 10
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: predictor-api
spec:
  selector:
    app: predictor-api
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000